version: '3'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: django-project
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data

  backend:
    build:
      context: ./django_project
    privileged: true
    volumes:
      - "media:/django_project/media"
    restart: always
    expose:
      - 8000
    command: bash -c "
      python manage.py migrate &&
      gunicorn django_project.wsgi -b 0.0.0.0:8000
      "
    environment:
      DJANGO_SETTINGS_MODULE: django_project.settings.site_1
    depends_on:
      - db
#
  nginx:
    build:
      context: ./nginx
    ports:
      - '8002:8002'
    depends_on:
      - backend

volumes:
  media: