# Generated by Django 4.0.4 on 2022-05-25 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название товара')),
                ('receipt_date', models.DateField(default=datetime.date.today, verbose_name='Дата поступления')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена товара')),
                ('vendor_name', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Имя поставщика')),
                ('item_unit', models.CharField(default='шт', max_length=10, verbose_name='Единица измерения')),
            ],
        ),
    ]
