# Generated by Django 4.0.4 on 2022-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_items', '0002_section_shopitem_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание раздела'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='sections',
            field=models.ManyToManyField(related_name='shop_items', to='shop_items.section', verbose_name='Разделы'),
        ),
    ]
