# Generated by Django 4.0.4 on 2022-06-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_items', '0006_shopitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(null=True, upload_to='item_images', verbose_name='Изображение товара'),
        ),
    ]
